project:
  type: website
  output-dir: docs
website:
  title: "Bradford Johnson"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: envelope
        href: mailto:bradfordljohnson@outlook.com
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

